// Digital clock

let time = document.getElementById("current-time");

setInterval(() =>{
let d = new Date();

var monthNames = ["Jan,", "Feb,", "Mar,", "Apr,", "May,", "Jun,", "Jul,", "Aug,", "Sep,", "Oct,", "Nov,", "Dec,"];
var theMonth = d.getMonth();
var nameOfMonth = monthNames[theMonth];
var dayNames = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
var theDay = d.getDay();
var nameOfDay = dayNames[theDay];
var theDate = d.getDate();

document.getElementById('day').innerText = nameOfMonth;
document.getElementById('day2').innerText = nameOfDay;
document.getElementById('day3').innerText = theDate;
time.innerHTML = d.toLocaleTimeString();
},1000);


// Positive Integer

function positiveinteger(){
    var userInput = document.getElementById("positiveinteger").value;
    document.getElementById("pi1").innerText = userInput;
    var roundOff = Math.round(userInput);
    document.getElementById("pi2").innerText = roundOff;
    var floor = Math.floor(userInput);
    document.getElementById("pi3").innerText = floor;
    var ceil = Math.ceil(userInput);
    document.getElementById("pi4").innerText = ceil;
}

// Negative Integer

function negativeinteger(){
    var userInput = document.getElementById("negativeinteger").value;
    var negativeInteger = - + userInput;
    document.getElementById("ni1").innerText = negativeInteger;
    var roundOff = Math.round(negativeInteger);
    document.getElementById("ni2").innerText = roundOff;
    var floor = Math.floor(negativeInteger);
    document.getElementById("ni3").innerText = floor;
    var ceil = Math.ceil(negativeInteger);
    document.getElementById("ni4").innerText = ceil;
}

// Positive Floating

function positivefloating(){
    var userInput = document.getElementById("positivefloating").value;
    document.getElementById("pfp1").innerText = userInput;
    var roundOff = Math.round(userInput);
    document.getElementById("pfp2").innerText = roundOff;
    var floor = Math.floor(userInput);
    document.getElementById("pfp3").innerText = floor;
    var ceil = Math.ceil(userInput);
    document.getElementById("pfp4").innerText = ceil;
}

// Negative Floating

function negativefloating(){
    var userInput = document.getElementById("negativefloating").value;
    var negativeInteger = - + userInput;
    document.getElementById("nfp1").innerText = negativeInteger;
    var roundOff = Math.round(negativeInteger);
    document.getElementById("nfp2").innerText = roundOff;
    var floor = Math.floor(negativeInteger);
    document.getElementById("nfp3").innerText = floor;
    var ceil = Math.ceil(negativeInteger);
    document.getElementById("nfp4").innerText = ceil;
}

// Absolute Value

function absolutevalue(){
    var userInput = document.getElementById("avinput").value; 
    document.getElementById("unfav").innerText = userInput;
    var absoluteValue = Math.abs(userInput);
    document.getElementById("unfavr").innerText = absoluteValue;
}

// Dice Function

function dice(){
    var dice = Math.random();
    var randomDice = dice*6 + 1;
    var result = Math.floor(randomDice);
    document.getElementById("dice").innerText = result;
}

// Toss

function toss(){
    var toss = Math.random();
    var randomToss = toss*2 + 1;
    var result = Math.floor(randomToss);
    if(result == 1){
    document.getElementById("toss").innerText = "Heads" ;
    }
    if(result == 2){
        document.getElementById("toss").innerText = "Tails" ;
        }
}

// One to Hundred

function onetohundred(){
    var dice = Math.random();
    var randomDice = dice*100 + 1;
    var result = Math.floor(randomDice);
    document.getElementById("onetohundred").innerText = result;
}

// User Weight

function userweight(){
    var userInput = document.getElementById("userweight").value;
    var mainWeight = userInput;
    var poundWeight = mainWeight * 2.20 ;
    var gramWeight = mainWeight * 1000 ;
    var milliGramWeight = mainWeight * 1000000;
    document.getElementById("mainweight").innerText ="Your weight is " + mainWeight + " kg";
    document.getElementById("poundweight").innerText ="Your weight is " + poundWeight + " lb";
    document.getElementById("gramweight").innerText ="Your weight is " + gramWeight + " gram";
    document.getElementById("milligramweight").innerText ="Your weight is " + milliGramWeight + " milligram";
}

// Game 

function game(){
    randomNumber1 = Math.floor(Math.random() * (10 - 1 + 1)) + 1;
    document.getElementById("gamedata").innerText ="The random number generated by code is " + randomNumber1;
    var inputNumber = document.getElementById("gameinput");
    if (randomNumber1 === inputNumber) {
        // alert("Congratulations! number is matched");
        document.getElementById("gameresult").innerText += "Congratulations! number is matched";
    }
    else {
    // alert("Try again! number not matched");
    document.getElementById("gameresult").innerText += "Try again! number not matched";
    }
}

// Current Date

    var date = new Date();
    document.getElementById("currentdate2").innerText += "Current date is " + date;
    document.getElementById("gettingdate").innerText += "The Date is get from your browser via using new Date()"
    // var day = date.getDate;
    // document.getElementById("currentday2").innerText += "Current day is " + day;
    // document.getElementById
    // ("gettingday").innerText += "The Day is get via using new date.getDay()"
    var month = ["January","February","March","April","May","June","July","August","September","October","November","December"];

    // currentDate = new Date();
    var currentMonth = month[date.getMonth()];
    document.getElementById("currentday2").innerText += "Current month: " + currentMonth ;
    document.getElementById("gettingday").innerText += "The Month is get via using new month[currentDate.getMonth()]"
    
    var currentDay = day[date.getDay()];
    if (currentDay === "Sun" || currentDay === "Sat"  ) {
    document.getElementById("currentmonth2").innerHTML += "It's Fun day ";
    }
    else {
    document.getElementById("currentmonth2").innerHTML += "It's Work day";
    }
    document.getElementById("gettingmonth").innerText += "The Day is get via using new day[date.getDay()]"


 // Age Calculator
 
    function age(){
        var currentDate = new Date();
        var currentYear = currentDate.getFullYear();
        var userInput = document.getElementById("ageinput").value;
        var resultYear = currentYear - userInput;
        var resultMonth = resultYear * 12;
        document.getElementById("ageresult").innerText += "You Are " + resultYear + " years Old.";
        document.getElementById("ageresult2").innerText += "You are " + resultMonth + " months Old."
        document.getElementById("agedata").innerText += "Your age is get via ('CuurentYear - Your Input') ."
        
    }

// Electric Bill

    function bill(){
        var userName = document.getElementById("nameinput").value;
        var a = userName;
        var userUnit = document.getElementById("unitinput").value;
        var result = userUnit * 28;
        document.getElementById("charges").innerText = "Dear " + a +  ", Charges per unit is 28Rs, "
        document.getElementById("billdata").innerText += "You have to pay " + result + "Rs"
    }





// var today = new Date();
// var date = today.getFullYear()+"-"+(today.getMonth()+1)+"-"+ today.getDate();
// document.write(date);

// var today = new Date();
// var time = today.getHours() + ":" + today.getMinutes() + ":" + today.getSeconds();
// document.write(time);


